# permissions for end users to edit discoveries.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: discovery-editor-role
rules:
- apiGroups:
  - discovery.lqh.xzy
  resources:
  - discoveries
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - discovery.lqh.xzy
  resources:
  - discoveries/status
  verbs:
  - get
